project_id = "kbazzjpfszotqmzmyzwf"

[functions.analyze-drawing]
verify_jwt = false

[functions.cnc-ai-chat]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.update-currency-forecasts]
verify_jwt = false

[functions.analyze-spec]
verify_jwt = false